AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM Lambda Express API"
Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"  
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs22.x
      MemorySize: !Ref MaxMemory
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
      Timeout: 300
      CodeUri: ./
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
Parameters:
  ApiKey:
    Type: String
    Description: API key used to authenticate the request
    Default: 0000
  MaxMemory:
    Type: Number
    Description: Maximum megabytes of memory for the Lambda function
    Default: 128
Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/"
