# filepath: .github/workflows/deploy.yml
name: SAM Deploy

# Required for GitHub Actions OIDC to work with AWS
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    #environment: production
    env:
      STACK_NAME: ${{ vars.STACK_NAME }}  # Make sure to set this variable in repository settings
      MAX_MEMORY: ${{ vars.MAX_MEMORY }}  # Set in repository settings
      API_KEY: ${{ vars.API_KEY }}
      REGION: ${{ vars.REGION }}
      ROLE: ${{ vars.AWS_ROLE_ARN }}        # Set in repository settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Build SAM application
        run: sam build
      
      - name: Deploy SAM application
        run: |
          sam deploy --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --resolve-s3 \
          --stack-name ${{ env.STACK_NAME }} \
          --parameter-overrides \
          ParameterKey=MaxMemory,ParameterValue=${{ env.MAX_MEMORY }} \
          ParameterKey=ApiKey,ParameterValue="${{ env.API_KEY }}" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM